from playwright.sync_api import sync_playwright
import re
B='http://localhost:3000'
ok=[]
def check(name,cond,extra=''):
    ok.append(cond); print(('PASS ' if cond else 'FAIL ')+name, extra)
with sync_playwright() as p:
    b=p.chromium.launch(); pg=b.new_page(viewport={'width':1440,'height':860})
    errs=[]; pg.on('pageerror',lambda e:errs.append(str(e)))
    pg.goto(B); pg.wait_for_timeout(1500); pg.screenshot(path='/tmp/m3_home.png')
    check('home recent list', pg.locator('a[href^="/meetings/"]').count()>=5)
    pg.get_by_role('tab',name='AI Feed').click(); check('ai feed', pg.get_by_text('Recommended Skills').is_visible())
    pg.locator('main').get_by_text('Settings',exact=True).click(); pg.wait_for_timeout(200); check('meeting settings modal', pg.get_by_text('Meeting Settings').is_visible()); pg.get_by_role('button',name='Save').click()
    # library
    pg.goto(B+'/meetings'); pg.wait_for_timeout(1500); pg.screenshot(path='/tmp/m3_lib.png')
    n=pg.locator('a[href^="/meetings/"]').count(); check('library lists 6',n==6,n)
    pg.get_by_label('Search meetings').fill('Northwind'); pg.wait_for_timeout(900)
    check('search filters',pg.locator('a[href^="/meetings/"]').count()==2)
    pg.get_by_label('Search meetings').fill(''); pg.wait_for_timeout(700)
    pg.get_by_role('button',name=re.compile('Filters')).click(); pg.get_by_label('Participant').select_option(label='Maya Chen'); pg.wait_for_timeout(800)
    m=pg.locator('a[href^="/meetings/"]').count(); check('participant filter narrows',0<m<6,m)
    pg.get_by_role('button',name='Clear filters').click(); pg.wait_for_timeout(700)
    pg.get_by_label('Date').select_option('today'); pg.wait_for_timeout(800); print('today count',pg.locator('a[href^="/meetings/"]').count())
    pg.get_by_role('button',name='Clear filters').click(); pg.keyboard.press('Escape')
    pg.get_by_role('button',name='Uploads').click(); pg.wait_for_timeout(400); check('uploads channel shows only upload',pg.locator('a[href^="/meetings/"]').count()==1)
    # detail
    pg.goto(B+'/meetings/1'); pg.wait_for_timeout(1800); pg.screenshot(path='/tmp/m3_detail.png')
    rows=pg.locator('[aria-label="Transcript"] div.group'); check('segments render',rows.count()>10,rows.count())
    rows.nth(5).click(); pg.wait_for_timeout(300)
    t=pg.locator('text=/\\d+:\\d\\d \\/ \\d+:\\d\\d/').first.inner_text(); check('click line seeks',not t.startswith('0:00 /'),t)
    pg.get_by_label('Seek').focus(); pg.keyboard.press('Home'); pg.wait_for_timeout(300)
    check('seek bar moves active line to first', 'border-accent' in (rows.nth(0).get_attribute('class') or ''))
    pg.get_by_label('Playback speed').click(); pg.get_by_label('Play').first.click(); pg.wait_for_timeout(2300)
    t2=pg.locator('text=/\\d+:\\d\\d \\/ \\d+:\\d\\d/').first.inner_text(); check('simulated play advances',not t2.startswith('0:00 /'),t2); pg.get_by_label('Pause').first.click()
    for q in ['(','?','[a','latency']:
        pg.get_by_label('Search transcript').fill(q); pg.wait_for_timeout(250)
    check('search highlights', pg.locator('mark').count()>0, pg.locator('mark').count()); check('match counter', pg.get_by_text(re.compile(r'\d+ / \d+')).count()>0)
    pg.get_by_label('Search transcript').fill('(roadmap?'); pg.wait_for_timeout(250); check('regex chars no crash',len(errs)==0,errs)
    pg.get_by_label('Search transcript').fill('')
    # tabs
    pg.get_by_role('tab',name=re.compile('Action items')).click(); pg.wait_for_timeout(300)
    boxes=pg.get_by_role('checkbox'); before=boxes.first.get_attribute('aria-checked'); boxes.first.click(); pg.wait_for_timeout(700)
    after=pg.get_by_role('checkbox').first.get_attribute('aria-checked'); check('toggle action item',before!=after,(before,after)); pg.get_by_role('checkbox').first.click(); pg.wait_for_timeout(500)
    pg.get_by_label('New action item').fill('Playwright added item'); pg.get_by_label('Assignee').last.fill('Maya Chen'); pg.get_by_role('button',name='Add',exact=True).click(); pg.wait_for_timeout(800)
    check('add action item',pg.locator('input[value=\"Playwright added item\"]').count()==1)
    pg.locator('input[value=\"Playwright added item\"]').fill('Edited by test'); pg.keyboard.press('Enter'); pg.wait_for_timeout(800)
    check('edit action item',pg.locator('input[value=\"Edited by test\"]').count()==1)
    pg.get_by_label('Delete action item').last.click(); pg.wait_for_timeout(700); check('delete action item',pg.locator('input[value=\"Edited by test\"]').count()==0)
    pg.get_by_role('tab',name='Outline').click(); pg.locator('ol button').nth(1).click(); pg.wait_for_timeout(300); check('chapter click seeks',not pg.locator('text=/\\d+:\\d\\d \\/ \\d+:\\d\\d/').first.inner_text().startswith('0:00 /'))
    pg.get_by_role('tab',name='Ask Fred').click(); pg.get_by_label('Ask Fred').last.fill('What are the action items?'); pg.keyboard.press('Enter'); pg.wait_for_timeout(2500); check('ask fred answers',pg.get_by_text('action item',exact=False).count()>2)
    pg.screenshot(path='/tmp/m3_askfred.png')
    # create by paste, edit, delete
    pg.goto(B+'/uploads'); pg.wait_for_timeout(800)
    pg.get_by_role('tab',name='Paste transcript').click(); pg.get_by_placeholder('E.g. Weekly product sync').fill('E2E Test Sync')
    pg.get_by_placeholder('Alex Rivers, alex@acme.com').fill('Sam Test\nPat Test')
    pg.locator('textarea').last.fill('Sam Test: Welcome. Today we discuss the launch plan and pricing.\nPat Test: Sam, can you send the pricing deck by Friday?\nSam Test: Sure, I will send the pricing deck by Friday. We also decided to delay the launch to November.')
    pg.get_by_role('button',name='Create meeting').click(); pg.wait_for_url(re.compile(r'/meetings/\d+$')); pg.wait_for_timeout(1500)
    check('created + notes generated', pg.get_by_text('E2E Test Sync').count()>0 and pg.get_by_text('pricing').count()>0); pg.screenshot(path='/tmp/m3_created.png')
    pg.get_by_role('tab',name=re.compile('Action items')).click(); pg.wait_for_timeout(300); print('items:',[pg.get_by_label('Action item text').nth(i).input_value() for i in range(pg.get_by_label('Action item text').count())])
    pg.get_by_role('button',name='Edit',exact=True).click(); pg.get_by_label('Title',exact=True).fill('E2E Renamed'); pg.get_by_role('button',name='Save',exact=True).click(); pg.wait_for_timeout(900); check('edit title',pg.get_by_role('heading',name='E2E Renamed').count()==1)
    pg.get_by_label('Delete meeting').click(); pg.locator('button.bg-red-500').click(); pg.wait_for_url(B+'/meetings'); pg.wait_for_timeout(900); check('deleted',pg.get_by_text('E2E Renamed').count()==0)
    pg.goto(B+'/tasks'); pg.wait_for_timeout(1200); pg.screenshot(path='/tmp/m3_tasks.png'); check('tasks list',pg.get_by_role('checkbox').count()>5,pg.get_by_role('checkbox').count())
    print('page errors:',errs); b.close()
print('ALL PASS' if all(ok) else 'SOME FAIL')
